#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
# Simple password manager
# Copyright (c) 2011-2019 Michael Buesch <m@bues.ch>
# Licensed under the GNU/GPL version 2 or later.
"""

from libpwman.__main__ import main
import sys

if __name__ == "__main__":
	sys.exit(main())
