name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PWMAN_RAWGETPASS: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Cache Rust
        uses: actions/cache@v6
        with:
          path: ~/.rustup
          key: rustup

      - name: Install dependencies
        run: sudo apt install python3-pyaes python3-pycryptodome python3-argon2 python3-cffi expect

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Run tests
        run: sh ./tests/run.sh

      - name: Show help
        run: python3 ./pwman --no-mlock --help

      - name: Run basic read command
        run: expect -c "spawn python3 ./pwman --no-mlock -c ls ./tests/test_database_v1.db" -c "expect \"Master passphrase\" { send \"test\\r\"; exp_continue }" -c "catch wait res; exit [lindex \$res 3]"

      - name: Run example script with --call-pyfile
        run: |
          cp ./tests/test_database_v1.db ./tests/test_database_v1.db.tmp
          expect -c "spawn python3 ./pwman --no-mlock --call-pyfile ./examplescript.py ./tests/test_database_v1.db.tmp" -c "expect \"Master passphrase\" { send \"test\\r\"; exp_continue }" -c "catch wait res; exit [lindex \$res 3]"

      - name: Run example script with --call-pymod
        run: |
          cp ./tests/test_database_v1.db ./tests/test_database_v1.db.tmp
          expect -c "spawn python3 ./pwman --no-mlock --call-pymod examplescript.py ./tests/test_database_v1.db.tmp" -c "expect \"Master passphrase\" { send \"test\\r\"; exp_continue }" -c "catch wait res; exit [lindex \$res 3]"

# vim: ts=2 sw=2 expandtab
